spring.application.name=invoice

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_management
spring.datasource.username=yasuka0186
spring.datasource.password=yasuka0186
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=debug
logging.level.org.flywaydb=info
